# Generated by Django 2.1.5 on 2019-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190226_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Addr2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
