# Generated by Django 2.1.5 on 2019-02-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190226_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettingsType', models.CharField(choices=[('Text', 'Text'), ('Push', 'Push Notification'), ('Email', 'Email')], max_length=50)),
                ('TaskCompleted', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3)),
                ('Likes', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3)),
                ('Comments', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3)),
                ('TaskPicked', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3)),
                ('UserFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
