# Generated by Django 2.1.5 on 2019-02-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20190226_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=1200)),
                ('CreatedTS', models.DateTimeField(auto_now_add=True)),
                ('UpdatedTS', models.DateTimeField(auto_now=True)),
                ('TaskFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Task', to='tasks.Task')),
                ('UserFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_task', to=settings.AUTH_USER_MODEL)),
                ('UserFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
