# Generated by Django 2.1.5 on 2019-02-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskcomment_tasklike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklike',
            name='TaskFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_task', to='tasks.Task'),
        ),
    ]
